### ISSUE TITLE
Better defaults for status icons in plugins

### ISSUE THREAD

**Issue by enrh** [enasisnetwork/enrobie#119]
Currently there are several instances of this in my configuration, and in hindsight it seems a poor design not to include sane defaults in each plugin.

```yaml
    status:
      dsc: ':robot:'
      irc: 🤖
      mtm: ':robot:'
```
